// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/agentd/v1/agent.proto

package agentdv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Command         string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	TimeoutMs       uint32                 `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`                     // default: 30000
	Interactive     bool                   `protobuf:"varint,3,opt,name=interactive,proto3" json:"interactive,omitempty"`                                  // keep alive on timeout (for REPLs, TUIs)
	RunInBackground bool                   `protobuf:"varint,4,opt,name=run_in_background,json=runInBackground,proto3" json:"run_in_background,omitempty"` // return task_id immediately
	TailLines       uint32                 `protobuf:"varint,5,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`                     // return only last N lines of output
	HeadLines       uint32                 `protobuf:"varint,6,opt,name=head_lines,json=headLines,proto3" json:"head_lines,omitempty"`                     // return only first N lines of output
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *ExecRequest) GetInteractive() bool {
	if x != nil {
		return x.Interactive
	}
	return false
}

func (x *ExecRequest) GetRunInBackground() bool {
	if x != nil {
		return x.RunInBackground
	}
	return false
}

func (x *ExecRequest) GetTailLines() uint32 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

func (x *ExecRequest) GetHeadLines() uint32 {
	if x != nil {
		return x.HeadLines
	}
	return 0
}

type ExecResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "completed", "awaiting_input", "timeout"
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Set when status = "completed"
	ExitCode int32  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout   string `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr   string `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	// Set when status = "awaiting_input"
	PromptType string `protobuf:"bytes,5,opt,name=prompt_type,json=promptType,proto3" json:"prompt_type,omitempty"` // "password", "confirmation", "interactive"
	PromptText string `protobuf:"bytes,6,opt,name=prompt_text,json=promptText,proto3" json:"prompt_text,omitempty"`
	// Set when interactive = true and status = "awaiting_input"
	Screen string `protobuf:"bytes,7,opt,name=screen,proto3" json:"screen,omitempty"` // current terminal screen content
	// Set when run_in_background = true
	TaskId string `protobuf:"bytes,8,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Output truncation info
	Truncated     bool   `protobuf:"varint,9,opt,name=truncated,proto3" json:"truncated,omitempty"`
	TotalLines    uint32 `protobuf:"varint,10,opt,name=total_lines,json=totalLines,proto3" json:"total_lines,omitempty"`
	ShownLines    uint32 `protobuf:"varint,11,opt,name=shown_lines,json=shownLines,proto3" json:"shown_lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ExecResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecResponse) GetPromptType() string {
	if x != nil {
		return x.PromptType
	}
	return ""
}

func (x *ExecResponse) GetPromptText() string {
	if x != nil {
		return x.PromptText
	}
	return ""
}

func (x *ExecResponse) GetScreen() string {
	if x != nil {
		return x.Screen
	}
	return ""
}

func (x *ExecResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExecResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *ExecResponse) GetTotalLines() uint32 {
	if x != nil {
		return x.TotalLines
	}
	return 0
}

func (x *ExecResponse) GetShownLines() uint32 {
	if x != nil {
		return x.ShownLines
	}
	return 0
}

type InputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"` // text input (newline appended automatically)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputRequest) Reset() {
	*x = InputRequest{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputRequest) ProtoMessage() {}

func (x *InputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputRequest.ProtoReflect.Descriptor instead.
func (*InputRequest) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *InputRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type InputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "completed", "awaiting_input", "timeout"
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	PromptType    string                 `protobuf:"bytes,5,opt,name=prompt_type,json=promptType,proto3" json:"prompt_type,omitempty"`
	PromptText    string                 `protobuf:"bytes,6,opt,name=prompt_text,json=promptText,proto3" json:"prompt_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputResponse) Reset() {
	*x = InputResponse{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputResponse) ProtoMessage() {}

func (x *InputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputResponse.ProtoReflect.Descriptor instead.
func (*InputResponse) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *InputResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InputResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *InputResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *InputResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *InputResponse) GetPromptType() string {
	if x != nil {
		return x.PromptType
	}
	return ""
}

func (x *InputResponse) GetPromptText() string {
	if x != nil {
		return x.PromptText
	}
	return ""
}

type RawInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"` // raw bytes sent directly to PTY
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawInputRequest) Reset() {
	*x = RawInputRequest{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawInputRequest) ProtoMessage() {}

func (x *RawInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawInputRequest.ProtoReflect.Descriptor instead.
func (*RawInputRequest) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *RawInputRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type RawInputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                      // "completed", "awaiting_input"
	Screen        string                 `protobuf:"bytes,2,opt,name=screen,proto3" json:"screen,omitempty"`                      // current terminal screen content
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"` // set when status = "completed"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawInputResponse) Reset() {
	*x = RawInputResponse{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawInputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawInputResponse) ProtoMessage() {}

func (x *RawInputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawInputResponse.ProtoReflect.Descriptor instead.
func (*RawInputResponse) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *RawInputResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RawInputResponse) GetScreen() string {
	if x != nil {
		return x.Screen
	}
	return ""
}

func (x *RawInputResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type InterruptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterruptRequest) Reset() {
	*x = InterruptRequest{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterruptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterruptRequest) ProtoMessage() {}

func (x *InterruptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterruptRequest.ProtoReflect.Descriptor instead.
func (*InterruptRequest) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{6}
}

type InterruptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterruptResponse) Reset() {
	*x = InterruptResponse{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterruptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterruptResponse) ProtoMessage() {}

func (x *InterruptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterruptResponse.ProtoReflect.Descriptor instead.
func (*InterruptResponse) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *InterruptResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TaskOutputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskOutputRequest) Reset() {
	*x = TaskOutputRequest{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskOutputRequest) ProtoMessage() {}

func (x *TaskOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskOutputRequest.ProtoReflect.Descriptor instead.
func (*TaskOutputRequest) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *TaskOutputRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskOutputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "running", "completed"
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskOutputResponse) Reset() {
	*x = TaskOutputResponse{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskOutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskOutputResponse) ProtoMessage() {}

func (x *TaskOutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskOutputResponse.ProtoReflect.Descriptor instead.
func (*TaskOutputResponse) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *TaskOutputResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskOutputResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TaskOutputResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *TaskOutputResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

type TaskStopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStopRequest) Reset() {
	*x = TaskStopRequest{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStopRequest) ProtoMessage() {}

func (x *TaskStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStopRequest.ProtoReflect.Descriptor instead.
func (*TaskStopRequest) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *TaskStopRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskStopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStopResponse) Reset() {
	*x = TaskStopResponse{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStopResponse) ProtoMessage() {}

func (x *TaskStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStopResponse.ProtoReflect.Descriptor instead.
func (*TaskStopResponse) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{11}
}

type FileGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Encoding      string                 `protobuf:"bytes,2,opt,name=encoding,proto3" json:"encoding,omitempty"` // "text" (default) or "base64"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileGetRequest) Reset() {
	*x = FileGetRequest{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileGetRequest) ProtoMessage() {}

func (x *FileGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileGetRequest.ProtoReflect.Descriptor instead.
func (*FileGetRequest) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *FileGetRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileGetRequest) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

type FileGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Checksum      string                 `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"` // SHA256
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileGetResponse) Reset() {
	*x = FileGetResponse{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileGetResponse) ProtoMessage() {}

func (x *FileGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileGetResponse.ProtoReflect.Descriptor instead.
func (*FileGetResponse) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *FileGetResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *FileGetResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileGetResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *FileGetResponse) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type FilePutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Encoding      string                 `protobuf:"bytes,3,opt,name=encoding,proto3" json:"encoding,omitempty"` // "text" (default) or "base64"
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`         // e.g. "0644"
	CreateDirs    bool                   `protobuf:"varint,5,opt,name=create_dirs,json=createDirs,proto3" json:"create_dirs,omitempty"`
	Overwrite     bool                   `protobuf:"varint,6,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilePutRequest) Reset() {
	*x = FilePutRequest{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilePutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePutRequest) ProtoMessage() {}

func (x *FilePutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePutRequest.ProtoReflect.Descriptor instead.
func (*FilePutRequest) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *FilePutRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FilePutRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *FilePutRequest) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *FilePutRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *FilePutRequest) GetCreateDirs() bool {
	if x != nil {
		return x.CreateDirs
	}
	return false
}

func (x *FilePutRequest) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

type FilePutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Checksum      string                 `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilePutResponse) Reset() {
	*x = FilePutResponse{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilePutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePutResponse) ProtoMessage() {}

func (x *FilePutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePutResponse.ProtoReflect.Descriptor instead.
func (*FilePutResponse) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *FilePutResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FilePutResponse) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type FileMoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMoveRequest) Reset() {
	*x = FileMoveRequest{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMoveRequest) ProtoMessage() {}

func (x *FileMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMoveRequest.ProtoReflect.Descriptor instead.
func (*FileMoveRequest) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *FileMoveRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *FileMoveRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type FileMoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMoveResponse) Reset() {
	*x = FileMoveResponse{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMoveResponse) ProtoMessage() {}

func (x *FileMoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMoveResponse.ProtoReflect.Descriptor instead.
func (*FileMoveResponse) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{17}
}

type FileGetChunkedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`                        // byte offset to read from
	ChunkSize     int32                  `protobuf:"varint,3,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"` // bytes to read (default: 1MB, max: 10MB)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileGetChunkedRequest) Reset() {
	*x = FileGetChunkedRequest{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileGetChunkedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileGetChunkedRequest) ProtoMessage() {}

func (x *FileGetChunkedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileGetChunkedRequest.ProtoReflect.Descriptor instead.
func (*FileGetChunkedRequest) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{18}
}

func (x *FileGetChunkedRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileGetChunkedRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileGetChunkedRequest) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

type FileGetChunkedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`                                     // raw chunk bytes
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`                                // offset this chunk starts at
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`                                    // actual bytes in this chunk
	TotalSize     int64                  `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`         // total file size
	Checksum      string                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`                             // SHA256 of this chunk
	FileChecksum  string                 `protobuf:"bytes,6,opt,name=file_checksum,json=fileChecksum,proto3" json:"file_checksum,omitempty"` // SHA256 of entire file (only in first chunk)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileGetChunkedResponse) Reset() {
	*x = FileGetChunkedResponse{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileGetChunkedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileGetChunkedResponse) ProtoMessage() {}

func (x *FileGetChunkedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileGetChunkedResponse.ProtoReflect.Descriptor instead.
func (*FileGetChunkedResponse) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{19}
}

func (x *FileGetChunkedResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileGetChunkedResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileGetChunkedResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileGetChunkedResponse) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *FileGetChunkedResponse) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *FileGetChunkedResponse) GetFileChecksum() string {
	if x != nil {
		return x.FileChecksum
	}
	return ""
}

type FilePutChunkedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                                // raw chunk bytes
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`                           // byte offset to write at
	TotalSize     int64                  `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`    // total file size (for pre-allocation, first chunk)
	Checksum      string                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`                        // SHA256 of this chunk (for verification)
	Mode          string                 `protobuf:"bytes,6,opt,name=mode,proto3" json:"mode,omitempty"`                                // file permissions (e.g. "0644", first chunk only)
	CreateDirs    bool                   `protobuf:"varint,7,opt,name=create_dirs,json=createDirs,proto3" json:"create_dirs,omitempty"` // create parent directories (first chunk only)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilePutChunkedRequest) Reset() {
	*x = FilePutChunkedRequest{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilePutChunkedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePutChunkedRequest) ProtoMessage() {}

func (x *FilePutChunkedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePutChunkedRequest.ProtoReflect.Descriptor instead.
func (*FilePutChunkedRequest) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{20}
}

func (x *FilePutChunkedRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FilePutChunkedRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FilePutChunkedRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FilePutChunkedRequest) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *FilePutChunkedRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *FilePutChunkedRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *FilePutChunkedRequest) GetCreateDirs() bool {
	if x != nil {
		return x.CreateDirs
	}
	return false
}

type FilePutChunkedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  int64                  `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"` // bytes written in this chunk
	TotalWritten  int64                  `protobuf:"varint,2,opt,name=total_written,json=totalWritten,proto3" json:"total_written,omitempty"` // total bytes written so far
	Checksum      string                 `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`                              // SHA256 of entire file (only when complete)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilePutChunkedResponse) Reset() {
	*x = FilePutChunkedResponse{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilePutChunkedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePutChunkedResponse) ProtoMessage() {}

func (x *FilePutChunkedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePutChunkedResponse.ProtoReflect.Descriptor instead.
func (*FilePutChunkedResponse) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{21}
}

func (x *FilePutChunkedResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *FilePutChunkedResponse) GetTotalWritten() int64 {
	if x != nil {
		return x.TotalWritten
	}
	return 0
}

func (x *FilePutChunkedResponse) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type PortExposeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          uint32                 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`                                // optional: custom domain (e.g., "app.example.com")
	CfToken       string                 `protobuf:"bytes,3,opt,name=cf_token,json=cfToken,proto3" json:"cf_token,omitempty"`               // optional: Cloudflare API token for custom domain
	CfZoneId      string                 `protobuf:"bytes,4,opt,name=cf_zone_id,json=cfZoneId,proto3" json:"cf_zone_id,omitempty"`          // optional: Cloudflare zone ID for custom domain
	CfAccountId   string                 `protobuf:"bytes,5,opt,name=cf_account_id,json=cfAccountId,proto3" json:"cf_account_id,omitempty"` // optional: Cloudflare account ID for custom domain
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortExposeRequest) Reset() {
	*x = PortExposeRequest{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortExposeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortExposeRequest) ProtoMessage() {}

func (x *PortExposeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortExposeRequest.ProtoReflect.Descriptor instead.
func (*PortExposeRequest) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{22}
}

func (x *PortExposeRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PortExposeRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *PortExposeRequest) GetCfToken() string {
	if x != nil {
		return x.CfToken
	}
	return ""
}

func (x *PortExposeRequest) GetCfZoneId() string {
	if x != nil {
		return x.CfZoneId
	}
	return ""
}

func (x *PortExposeRequest) GetCfAccountId() string {
	if x != nil {
		return x.CfAccountId
	}
	return ""
}

type PortExposeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"` // set if custom domain was used
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortExposeResponse) Reset() {
	*x = PortExposeResponse{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortExposeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortExposeResponse) ProtoMessage() {}

func (x *PortExposeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortExposeResponse.ProtoReflect.Descriptor instead.
func (*PortExposeResponse) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{23}
}

func (x *PortExposeResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PortExposeResponse) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PortExposeResponse) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type PortUnexposeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Port  uint32                 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	// Optional: unbind only this domain from the port. If empty, all domains
	// (and the quick tunnel, if any) on the port are removed.
	Domain        string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortUnexposeRequest) Reset() {
	*x = PortUnexposeRequest{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortUnexposeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortUnexposeRequest) ProtoMessage() {}

func (x *PortUnexposeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortUnexposeRequest.ProtoReflect.Descriptor instead.
func (*PortUnexposeRequest) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{24}
}

func (x *PortUnexposeRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PortUnexposeRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type PortUnexposeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortUnexposeResponse) Reset() {
	*x = PortUnexposeResponse{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortUnexposeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortUnexposeResponse) ProtoMessage() {}

func (x *PortUnexposeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortUnexposeResponse.ProtoReflect.Descriptor instead.
func (*PortUnexposeResponse) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{25}
}

type PortListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortListRequest) Reset() {
	*x = PortListRequest{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortListRequest) ProtoMessage() {}

func (x *PortListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortListRequest.ProtoReflect.Descriptor instead.
func (*PortListRequest) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{26}
}

type PortListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ports         []*ExposedPort         `protobuf:"bytes,1,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortListResponse) Reset() {
	*x = PortListResponse{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortListResponse) ProtoMessage() {}

func (x *PortListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortListResponse.ProtoReflect.Descriptor instead.
func (*PortListResponse) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{27}
}

func (x *PortListResponse) GetPorts() []*ExposedPort {
	if x != nil {
		return x.Ports
	}
	return nil
}

type ExposedPort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          uint32                 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExposedPort) Reset() {
	*x = ExposedPort{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExposedPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExposedPort) ProtoMessage() {}

func (x *ExposedPort) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExposedPort.ProtoReflect.Descriptor instead.
func (*ExposedPort) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{28}
}

func (x *ExposedPort) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ExposedPort) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ExposedPort) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{29}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds uint64                 `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	// Unix ms of the last authenticated client call, 0 if none since boot.
	LastClientActivityUnixMs int64 `protobuf:"varint,3,opt,name=last_client_activity_unix_ms,json=lastClientActivityUnixMs,proto3" json:"last_client_activity_unix_ms,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentd_v1_agent_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_agentd_v1_agent_proto_rawDescGZIP(), []int{30}
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingResponse) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *PingResponse) GetLastClientActivityUnixMs() int64 {
	if x != nil {
		return x.LastClientActivityUnixMs
	}
	return 0
}

var File_proto_agentd_v1_agent_proto protoreflect.FileDescriptor

const file_proto_agentd_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/agentd/v1/agent.proto\x12\tagentd.v1\"\xd2\x01\n" +
	"\vExecRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\rR\ttimeoutMs\x12 \n" +
	"\vinteractive\x18\x03 \x01(\bR\vinteractive\x12*\n" +
	"\x11run_in_background\x18\x04 \x01(\bR\x0frunInBackground\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x05 \x01(\rR\ttailLines\x12\x1d\n" +
	"\n" +
	"head_lines\x18\x06 \x01(\rR\theadLines\"\xc6\x02\n" +
	"\fExecResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\tR\x06stderr\x12\x1f\n" +
	"\vprompt_type\x18\x05 \x01(\tR\n" +
	"promptType\x12\x1f\n" +
	"\vprompt_text\x18\x06 \x01(\tR\n" +
	"promptText\x12\x16\n" +
	"\x06screen\x18\a \x01(\tR\x06screen\x12\x17\n" +
	"\atask_id\x18\b \x01(\tR\x06taskId\x12\x1c\n" +
	"\ttruncated\x18\t \x01(\bR\ttruncated\x12\x1f\n" +
	"\vtotal_lines\x18\n" +
	" \x01(\rR\n" +
	"totalLines\x12\x1f\n" +
	"\vshown_lines\x18\v \x01(\rR\n" +
	"shownLines\"$\n" +
	"\fInputRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\"\xb6\x01\n" +
	"\rInputResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\tR\x06stderr\x12\x1f\n" +
	"\vprompt_type\x18\x05 \x01(\tR\n" +
	"promptType\x12\x1f\n" +
	"\vprompt_text\x18\x06 \x01(\tR\n" +
	"promptText\"'\n" +
	"\x0fRawInputRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\"_\n" +
	"\x10RawInputResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x16\n" +
	"\x06screen\x18\x02 \x01(\tR\x06screen\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\"\x12\n" +
	"\x10InterruptRequest\"+\n" +
	"\x11InterruptResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\",\n" +
	"\x11TaskOutputRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"y\n" +
	"\x12TaskOutputResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\tR\x06stderr\"*\n" +
	"\x0fTaskStopRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\x12\n" +
	"\x10TaskStopResponse\"@\n" +
	"\x0eFileGetRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1a\n" +
	"\bencoding\x18\x02 \x01(\tR\bencoding\"o\n" +
	"\x0fFileGetResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\tR\bchecksum\"\xad\x01\n" +
	"\x0eFilePutRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1a\n" +
	"\bencoding\x18\x03 \x01(\tR\bencoding\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\x12\x1f\n" +
	"\vcreate_dirs\x18\x05 \x01(\bR\n" +
	"createDirs\x12\x1c\n" +
	"\toverwrite\x18\x06 \x01(\bR\toverwrite\"A\n" +
	"\x0fFilePutResponse\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\x12\x1a\n" +
	"\bchecksum\x18\x02 \x01(\tR\bchecksum\"K\n" +
	"\x0fFileMoveRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\"\x12\n" +
	"\x10FileMoveResponse\"b\n" +
	"\x15FileGetChunkedRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x03 \x01(\x05R\tchunkSize\"\xb8\x01\n" +
	"\x16FileGetChunkedResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\x12\x1d\n" +
	"\n" +
	"total_size\x18\x04 \x01(\x03R\ttotalSize\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\tR\bchecksum\x12#\n" +
	"\rfile_checksum\x18\x06 \x01(\tR\ffileChecksum\"\xc7\x01\n" +
	"\x15FilePutChunkedRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x1d\n" +
	"\n" +
	"total_size\x18\x04 \x01(\x03R\ttotalSize\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\tR\bchecksum\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\tR\x04mode\x12\x1f\n" +
	"\vcreate_dirs\x18\a \x01(\bR\n" +
	"createDirs\"~\n" +
	"\x16FilePutChunkedResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x03R\fbytesWritten\x12#\n" +
	"\rtotal_written\x18\x02 \x01(\x03R\ftotalWritten\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\tR\bchecksum\"\x9c\x01\n" +
	"\x11PortExposeRequest\x12\x12\n" +
	"\x04port\x18\x01 \x01(\rR\x04port\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x19\n" +
	"\bcf_token\x18\x03 \x01(\tR\acfToken\x12\x1c\n" +
	"\n" +
	"cf_zone_id\x18\x04 \x01(\tR\bcfZoneId\x12\"\n" +
	"\rcf_account_id\x18\x05 \x01(\tR\vcfAccountId\"R\n" +
	"\x12PortExposeResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\"A\n" +
	"\x13PortUnexposeRequest\x12\x12\n" +
	"\x04port\x18\x01 \x01(\rR\x04port\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\"\x16\n" +
	"\x14PortUnexposeResponse\"\x11\n" +
	"\x0fPortListRequest\"@\n" +
	"\x10PortListResponse\x12,\n" +
	"\x05ports\x18\x01 \x03(\v2\x16.agentd.v1.ExposedPortR\x05ports\"K\n" +
	"\vExposedPort\x12\x12\n" +
	"\x04port\x18\x01 \x01(\rR\x04port\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\"\r\n" +
	"\vPingRequest\"\x8f\x01\n" +
	"\fPingResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x04R\ruptimeSeconds\x12>\n" +
	"\x1clast_client_activity_unix_ms\x18\x03 \x01(\x03R\x18lastClientActivityUnixMs2\xb1\b\n" +
	"\fAgentService\x127\n" +
	"\x04Exec\x12\x16.agentd.v1.ExecRequest\x1a\x17.agentd.v1.ExecResponse\x12:\n" +
	"\x05Input\x12\x17.agentd.v1.InputRequest\x1a\x18.agentd.v1.InputResponse\x12C\n" +
	"\bRawInput\x12\x1a.agentd.v1.RawInputRequest\x1a\x1b.agentd.v1.RawInputResponse\x12F\n" +
	"\tInterrupt\x12\x1b.agentd.v1.InterruptRequest\x1a\x1c.agentd.v1.InterruptResponse\x12I\n" +
	"\n" +
	"TaskOutput\x12\x1c.agentd.v1.TaskOutputRequest\x1a\x1d.agentd.v1.TaskOutputResponse\x12C\n" +
	"\bTaskStop\x12\x1a.agentd.v1.TaskStopRequest\x1a\x1b.agentd.v1.TaskStopResponse\x12@\n" +
	"\aFileGet\x12\x19.agentd.v1.FileGetRequest\x1a\x1a.agentd.v1.FileGetResponse\x12@\n" +
	"\aFilePut\x12\x19.agentd.v1.FilePutRequest\x1a\x1a.agentd.v1.FilePutResponse\x12C\n" +
	"\bFileMove\x12\x1a.agentd.v1.FileMoveRequest\x1a\x1b.agentd.v1.FileMoveResponse\x12U\n" +
	"\x0eFileGetChunked\x12 .agentd.v1.FileGetChunkedRequest\x1a!.agentd.v1.FileGetChunkedResponse\x12U\n" +
	"\x0eFilePutChunked\x12 .agentd.v1.FilePutChunkedRequest\x1a!.agentd.v1.FilePutChunkedResponse\x12I\n" +
	"\n" +
	"PortExpose\x12\x1c.agentd.v1.PortExposeRequest\x1a\x1d.agentd.v1.PortExposeResponse\x12O\n" +
	"\fPortUnexpose\x12\x1e.agentd.v1.PortUnexposeRequest\x1a\x1f.agentd.v1.PortUnexposeResponse\x12C\n" +
	"\bPortList\x12\x1a.agentd.v1.PortListRequest\x1a\x1b.agentd.v1.PortListResponse\x127\n" +
	"\x04Ping\x12\x16.agentd.v1.PingRequest\x1a\x17.agentd.v1.PingResponseB5Z3github.com/agend-sh/daemon/proto/agentd/v1;agentdv1b\x06proto3"

var (
	file_proto_agentd_v1_agent_proto_rawDescOnce sync.Once
	file_proto_agentd_v1_agent_proto_rawDescData []byte
)

func file_proto_agentd_v1_agent_proto_rawDescGZIP() []byte {
	file_proto_agentd_v1_agent_proto_rawDescOnce.Do(func() {
		file_proto_agentd_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agentd_v1_agent_proto_rawDesc), len(file_proto_agentd_v1_agent_proto_rawDesc)))
	})
	return file_proto_agentd_v1_agent_proto_rawDescData
}

var file_proto_agentd_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_proto_agentd_v1_agent_proto_goTypes = []any{
	(*ExecRequest)(nil),            // 0: agentd.v1.ExecRequest
	(*ExecResponse)(nil),           // 1: agentd.v1.ExecResponse
	(*InputRequest)(nil),           // 2: agentd.v1.InputRequest
	(*InputResponse)(nil),          // 3: agentd.v1.InputResponse
	(*RawInputRequest)(nil),        // 4: agentd.v1.RawInputRequest
	(*RawInputResponse)(nil),       // 5: agentd.v1.RawInputResponse
	(*InterruptRequest)(nil),       // 6: agentd.v1.InterruptRequest
	(*InterruptResponse)(nil),      // 7: agentd.v1.InterruptResponse
	(*TaskOutputRequest)(nil),      // 8: agentd.v1.TaskOutputRequest
	(*TaskOutputResponse)(nil),     // 9: agentd.v1.TaskOutputResponse
	(*TaskStopRequest)(nil),        // 10: agentd.v1.TaskStopRequest
	(*TaskStopResponse)(nil),       // 11: agentd.v1.TaskStopResponse
	(*FileGetRequest)(nil),         // 12: agentd.v1.FileGetRequest
	(*FileGetResponse)(nil),        // 13: agentd.v1.FileGetResponse
	(*FilePutRequest)(nil),         // 14: agentd.v1.FilePutRequest
	(*FilePutResponse)(nil),        // 15: agentd.v1.FilePutResponse
	(*FileMoveRequest)(nil),        // 16: agentd.v1.FileMoveRequest
	(*FileMoveResponse)(nil),       // 17: agentd.v1.FileMoveResponse
	(*FileGetChunkedRequest)(nil),  // 18: agentd.v1.FileGetChunkedRequest
	(*FileGetChunkedResponse)(nil), // 19: agentd.v1.FileGetChunkedResponse
	(*FilePutChunkedRequest)(nil),  // 20: agentd.v1.FilePutChunkedRequest
	(*FilePutChunkedResponse)(nil), // 21: agentd.v1.FilePutChunkedResponse
	(*PortExposeRequest)(nil),      // 22: agentd.v1.PortExposeRequest
	(*PortExposeResponse)(nil),     // 23: agentd.v1.PortExposeResponse
	(*PortUnexposeRequest)(nil),    // 24: agentd.v1.PortUnexposeRequest
	(*PortUnexposeResponse)(nil),   // 25: agentd.v1.PortUnexposeResponse
	(*PortListRequest)(nil),        // 26: agentd.v1.PortListRequest
	(*PortListResponse)(nil),       // 27: agentd.v1.PortListResponse
	(*ExposedPort)(nil),            // 28: agentd.v1.ExposedPort
	(*PingRequest)(nil),            // 29: agentd.v1.PingRequest
	(*PingResponse)(nil),           // 30: agentd.v1.PingResponse
}
var file_proto_agentd_v1_agent_proto_depIdxs = []int32{
	28, // 0: agentd.v1.PortListResponse.ports:type_name -> agentd.v1.ExposedPort
	0,  // 1: agentd.v1.AgentService.Exec:input_type -> agentd.v1.ExecRequest
	2,  // 2: agentd.v1.AgentService.Input:input_type -> agentd.v1.InputRequest
	4,  // 3: agentd.v1.AgentService.RawInput:input_type -> agentd.v1.RawInputRequest
	6,  // 4: agentd.v1.AgentService.Interrupt:input_type -> agentd.v1.InterruptRequest
	8,  // 5: agentd.v1.AgentService.TaskOutput:input_type -> agentd.v1.TaskOutputRequest
	10, // 6: agentd.v1.AgentService.TaskStop:input_type -> agentd.v1.TaskStopRequest
	12, // 7: agentd.v1.AgentService.FileGet:input_type -> agentd.v1.FileGetRequest
	14, // 8: agentd.v1.AgentService.FilePut:input_type -> agentd.v1.FilePutRequest
	16, // 9: agentd.v1.AgentService.FileMove:input_type -> agentd.v1.FileMoveRequest
	18, // 10: agentd.v1.AgentService.FileGetChunked:input_type -> agentd.v1.FileGetChunkedRequest
	20, // 11: agentd.v1.AgentService.FilePutChunked:input_type -> agentd.v1.FilePutChunkedRequest
	22, // 12: agentd.v1.AgentService.PortExpose:input_type -> agentd.v1.PortExposeRequest
	24, // 13: agentd.v1.AgentService.PortUnexpose:input_type -> agentd.v1.PortUnexposeRequest
	26, // 14: agentd.v1.AgentService.PortList:input_type -> agentd.v1.PortListRequest
	29, // 15: agentd.v1.AgentService.Ping:input_type -> agentd.v1.PingRequest
	1,  // 16: agentd.v1.AgentService.Exec:output_type -> agentd.v1.ExecResponse
	3,  // 17: agentd.v1.AgentService.Input:output_type -> agentd.v1.InputResponse
	5,  // 18: agentd.v1.AgentService.RawInput:output_type -> agentd.v1.RawInputResponse
	7,  // 19: agentd.v1.AgentService.Interrupt:output_type -> agentd.v1.InterruptResponse
	9,  // 20: agentd.v1.AgentService.TaskOutput:output_type -> agentd.v1.TaskOutputResponse
	11, // 21: agentd.v1.AgentService.TaskStop:output_type -> agentd.v1.TaskStopResponse
	13, // 22: agentd.v1.AgentService.FileGet:output_type -> agentd.v1.FileGetResponse
	15, // 23: agentd.v1.AgentService.FilePut:output_type -> agentd.v1.FilePutResponse
	17, // 24: agentd.v1.AgentService.FileMove:output_type -> agentd.v1.FileMoveResponse
	19, // 25: agentd.v1.AgentService.FileGetChunked:output_type -> agentd.v1.FileGetChunkedResponse
	21, // 26: agentd.v1.AgentService.FilePutChunked:output_type -> agentd.v1.FilePutChunkedResponse
	23, // 27: agentd.v1.AgentService.PortExpose:output_type -> agentd.v1.PortExposeResponse
	25, // 28: agentd.v1.AgentService.PortUnexpose:output_type -> agentd.v1.PortUnexposeResponse
	27, // 29: agentd.v1.AgentService.PortList:output_type -> agentd.v1.PortListResponse
	30, // 30: agentd.v1.AgentService.Ping:output_type -> agentd.v1.PingResponse
	16, // [16:31] is the sub-list for method output_type
	1,  // [1:16] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_agentd_v1_agent_proto_init() }
func file_proto_agentd_v1_agent_proto_init() {
	if File_proto_agentd_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agentd_v1_agent_proto_rawDesc), len(file_proto_agentd_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agentd_v1_agent_proto_goTypes,
		DependencyIndexes: file_proto_agentd_v1_agent_proto_depIdxs,
		MessageInfos:      file_proto_agentd_v1_agent_proto_msgTypes,
	}.Build()
	File_proto_agentd_v1_agent_proto = out.File
	file_proto_agentd_v1_agent_proto_goTypes = nil
	file_proto_agentd_v1_agent_proto_depIdxs = nil
}
