// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: proto/agentd/v1/agent.proto

package agentdv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_Exec_FullMethodName           = "/agentd.v1.AgentService/Exec"
	AgentService_Input_FullMethodName          = "/agentd.v1.AgentService/Input"
	AgentService_RawInput_FullMethodName       = "/agentd.v1.AgentService/RawInput"
	AgentService_Interrupt_FullMethodName      = "/agentd.v1.AgentService/Interrupt"
	AgentService_TaskOutput_FullMethodName     = "/agentd.v1.AgentService/TaskOutput"
	AgentService_TaskStop_FullMethodName       = "/agentd.v1.AgentService/TaskStop"
	AgentService_FileGet_FullMethodName        = "/agentd.v1.AgentService/FileGet"
	AgentService_FilePut_FullMethodName        = "/agentd.v1.AgentService/FilePut"
	AgentService_FileMove_FullMethodName       = "/agentd.v1.AgentService/FileMove"
	AgentService_FileGetChunked_FullMethodName = "/agentd.v1.AgentService/FileGetChunked"
	AgentService_FilePutChunked_FullMethodName = "/agentd.v1.AgentService/FilePutChunked"
	AgentService_PortExpose_FullMethodName     = "/agentd.v1.AgentService/PortExpose"
	AgentService_PortUnexpose_FullMethodName   = "/agentd.v1.AgentService/PortUnexpose"
	AgentService_PortList_FullMethodName       = "/agentd.v1.AgentService/PortList"
	AgentService_Ping_FullMethodName           = "/agentd.v1.AgentService/Ping"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService is the gRPC API exposed by the daemon inside each microVM.
// Clients send commands; the daemon executes them inside the box and returns
// structured results, including support for long-running and interactive
// applications.
type AgentServiceClient interface {
	// Execute a command. Returns stdout/stderr for completed commands,
	// or status "awaiting_input" if the process is waiting for input. The
	// daemon handles execution details, including interactive applications,
	// internally.
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
	// Send text input to a process waiting for input (password, confirmation).
	// Appends a newline automatically.
	Input(ctx context.Context, in *InputRequest, opts ...grpc.CallOption) (*InputResponse, error)
	// Send raw bytes to an interactive program (vim keystrokes, REPL code).
	// No newline appended — sends exactly what you provide.
	RawInput(ctx context.Context, in *RawInputRequest, opts ...grpc.CallOption) (*RawInputResponse, error)
	// Send SIGINT (Ctrl+C) to interrupt a running command.
	Interrupt(ctx context.Context, in *InterruptRequest, opts ...grpc.CallOption) (*InterruptResponse, error)
	// Get the output of a background task started with run_in_background.
	TaskOutput(ctx context.Context, in *TaskOutputRequest, opts ...grpc.CallOption) (*TaskOutputResponse, error)
	// Stop a running background task.
	TaskStop(ctx context.Context, in *TaskStopRequest, opts ...grpc.CallOption) (*TaskStopResponse, error)
	// Read a file's contents.
	FileGet(ctx context.Context, in *FileGetRequest, opts ...grpc.CallOption) (*FileGetResponse, error)
	// Write content to a file.
	FilePut(ctx context.Context, in *FilePutRequest, opts ...grpc.CallOption) (*FilePutResponse, error)
	// Move or rename a file.
	FileMove(ctx context.Context, in *FileMoveRequest, opts ...grpc.CallOption) (*FileMoveResponse, error)
	// Read a chunk of a file (for large file transfers).
	FileGetChunked(ctx context.Context, in *FileGetChunkedRequest, opts ...grpc.CallOption) (*FileGetChunkedResponse, error)
	// Write a chunk to a file (for large file transfers).
	FilePutChunked(ctx context.Context, in *FilePutChunkedRequest, opts ...grpc.CallOption) (*FilePutChunkedResponse, error)
	// Expose a port to the internet via Cloudflare Tunnel.
	PortExpose(ctx context.Context, in *PortExposeRequest, opts ...grpc.CallOption) (*PortExposeResponse, error)
	// Unexpose a previously exposed port.
	PortUnexpose(ctx context.Context, in *PortUnexposeRequest, opts ...grpc.CallOption) (*PortUnexposeResponse, error)
	// List currently exposed ports.
	PortList(ctx context.Context, in *PortListRequest, opts ...grpc.CallOption) (*PortListResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, AgentService_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Input(ctx context.Context, in *InputRequest, opts ...grpc.CallOption) (*InputResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InputResponse)
	err := c.cc.Invoke(ctx, AgentService_Input_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RawInput(ctx context.Context, in *RawInputRequest, opts ...grpc.CallOption) (*RawInputResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RawInputResponse)
	err := c.cc.Invoke(ctx, AgentService_RawInput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Interrupt(ctx context.Context, in *InterruptRequest, opts ...grpc.CallOption) (*InterruptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InterruptResponse)
	err := c.cc.Invoke(ctx, AgentService_Interrupt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) TaskOutput(ctx context.Context, in *TaskOutputRequest, opts ...grpc.CallOption) (*TaskOutputResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskOutputResponse)
	err := c.cc.Invoke(ctx, AgentService_TaskOutput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) TaskStop(ctx context.Context, in *TaskStopRequest, opts ...grpc.CallOption) (*TaskStopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskStopResponse)
	err := c.cc.Invoke(ctx, AgentService_TaskStop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FileGet(ctx context.Context, in *FileGetRequest, opts ...grpc.CallOption) (*FileGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileGetResponse)
	err := c.cc.Invoke(ctx, AgentService_FileGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FilePut(ctx context.Context, in *FilePutRequest, opts ...grpc.CallOption) (*FilePutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FilePutResponse)
	err := c.cc.Invoke(ctx, AgentService_FilePut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FileMove(ctx context.Context, in *FileMoveRequest, opts ...grpc.CallOption) (*FileMoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileMoveResponse)
	err := c.cc.Invoke(ctx, AgentService_FileMove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FileGetChunked(ctx context.Context, in *FileGetChunkedRequest, opts ...grpc.CallOption) (*FileGetChunkedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileGetChunkedResponse)
	err := c.cc.Invoke(ctx, AgentService_FileGetChunked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FilePutChunked(ctx context.Context, in *FilePutChunkedRequest, opts ...grpc.CallOption) (*FilePutChunkedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FilePutChunkedResponse)
	err := c.cc.Invoke(ctx, AgentService_FilePutChunked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) PortExpose(ctx context.Context, in *PortExposeRequest, opts ...grpc.CallOption) (*PortExposeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PortExposeResponse)
	err := c.cc.Invoke(ctx, AgentService_PortExpose_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) PortUnexpose(ctx context.Context, in *PortUnexposeRequest, opts ...grpc.CallOption) (*PortUnexposeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PortUnexposeResponse)
	err := c.cc.Invoke(ctx, AgentService_PortUnexpose_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) PortList(ctx context.Context, in *PortListRequest, opts ...grpc.CallOption) (*PortListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PortListResponse)
	err := c.cc.Invoke(ctx, AgentService_PortList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, AgentService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService is the gRPC API exposed by the daemon inside each microVM.
// Clients send commands; the daemon executes them inside the box and returns
// structured results, including support for long-running and interactive
// applications.
type AgentServiceServer interface {
	// Execute a command. Returns stdout/stderr for completed commands,
	// or status "awaiting_input" if the process is waiting for input. The
	// daemon handles execution details, including interactive applications,
	// internally.
	Exec(context.Context, *ExecRequest) (*ExecResponse, error)
	// Send text input to a process waiting for input (password, confirmation).
	// Appends a newline automatically.
	Input(context.Context, *InputRequest) (*InputResponse, error)
	// Send raw bytes to an interactive program (vim keystrokes, REPL code).
	// No newline appended — sends exactly what you provide.
	RawInput(context.Context, *RawInputRequest) (*RawInputResponse, error)
	// Send SIGINT (Ctrl+C) to interrupt a running command.
	Interrupt(context.Context, *InterruptRequest) (*InterruptResponse, error)
	// Get the output of a background task started with run_in_background.
	TaskOutput(context.Context, *TaskOutputRequest) (*TaskOutputResponse, error)
	// Stop a running background task.
	TaskStop(context.Context, *TaskStopRequest) (*TaskStopResponse, error)
	// Read a file's contents.
	FileGet(context.Context, *FileGetRequest) (*FileGetResponse, error)
	// Write content to a file.
	FilePut(context.Context, *FilePutRequest) (*FilePutResponse, error)
	// Move or rename a file.
	FileMove(context.Context, *FileMoveRequest) (*FileMoveResponse, error)
	// Read a chunk of a file (for large file transfers).
	FileGetChunked(context.Context, *FileGetChunkedRequest) (*FileGetChunkedResponse, error)
	// Write a chunk to a file (for large file transfers).
	FilePutChunked(context.Context, *FilePutChunkedRequest) (*FilePutChunkedResponse, error)
	// Expose a port to the internet via Cloudflare Tunnel.
	PortExpose(context.Context, *PortExposeRequest) (*PortExposeResponse, error)
	// Unexpose a previously exposed port.
	PortUnexpose(context.Context, *PortUnexposeRequest) (*PortUnexposeResponse, error)
	// List currently exposed ports.
	PortList(context.Context, *PortListRequest) (*PortListResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Exec(context.Context, *ExecRequest) (*ExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedAgentServiceServer) Input(context.Context, *InputRequest) (*InputResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Input not implemented")
}
func (UnimplementedAgentServiceServer) RawInput(context.Context, *RawInputRequest) (*RawInputResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RawInput not implemented")
}
func (UnimplementedAgentServiceServer) Interrupt(context.Context, *InterruptRequest) (*InterruptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Interrupt not implemented")
}
func (UnimplementedAgentServiceServer) TaskOutput(context.Context, *TaskOutputRequest) (*TaskOutputResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TaskOutput not implemented")
}
func (UnimplementedAgentServiceServer) TaskStop(context.Context, *TaskStopRequest) (*TaskStopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TaskStop not implemented")
}
func (UnimplementedAgentServiceServer) FileGet(context.Context, *FileGetRequest) (*FileGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FileGet not implemented")
}
func (UnimplementedAgentServiceServer) FilePut(context.Context, *FilePutRequest) (*FilePutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FilePut not implemented")
}
func (UnimplementedAgentServiceServer) FileMove(context.Context, *FileMoveRequest) (*FileMoveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FileMove not implemented")
}
func (UnimplementedAgentServiceServer) FileGetChunked(context.Context, *FileGetChunkedRequest) (*FileGetChunkedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FileGetChunked not implemented")
}
func (UnimplementedAgentServiceServer) FilePutChunked(context.Context, *FilePutChunkedRequest) (*FilePutChunkedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FilePutChunked not implemented")
}
func (UnimplementedAgentServiceServer) PortExpose(context.Context, *PortExposeRequest) (*PortExposeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PortExpose not implemented")
}
func (UnimplementedAgentServiceServer) PortUnexpose(context.Context, *PortUnexposeRequest) (*PortUnexposeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PortUnexpose not implemented")
}
func (UnimplementedAgentServiceServer) PortList(context.Context, *PortListRequest) (*PortListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PortList not implemented")
}
func (UnimplementedAgentServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Input_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Input(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Input_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Input(ctx, req.(*InputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RawInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawInputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RawInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RawInput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RawInput(ctx, req.(*RawInputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Interrupt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterruptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Interrupt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Interrupt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Interrupt(ctx, req.(*InterruptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_TaskOutput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskOutputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).TaskOutput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_TaskOutput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).TaskOutput(ctx, req.(*TaskOutputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_TaskStop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskStopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).TaskStop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_TaskStop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).TaskStop(ctx, req.(*TaskStopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FileGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FileGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_FileGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FileGet(ctx, req.(*FileGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FilePut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilePutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FilePut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_FilePut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FilePut(ctx, req.(*FilePutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FileMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileMoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FileMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_FileMove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FileMove(ctx, req.(*FileMoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FileGetChunked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileGetChunkedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FileGetChunked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_FileGetChunked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FileGetChunked(ctx, req.(*FileGetChunkedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FilePutChunked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilePutChunkedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FilePutChunked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_FilePutChunked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FilePutChunked(ctx, req.(*FilePutChunkedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_PortExpose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PortExposeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).PortExpose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_PortExpose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).PortExpose(ctx, req.(*PortExposeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_PortUnexpose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PortUnexposeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).PortUnexpose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_PortUnexpose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).PortUnexpose(ctx, req.(*PortUnexposeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_PortList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PortListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).PortList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_PortList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).PortList(ctx, req.(*PortListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentd.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Exec",
			Handler:    _AgentService_Exec_Handler,
		},
		{
			MethodName: "Input",
			Handler:    _AgentService_Input_Handler,
		},
		{
			MethodName: "RawInput",
			Handler:    _AgentService_RawInput_Handler,
		},
		{
			MethodName: "Interrupt",
			Handler:    _AgentService_Interrupt_Handler,
		},
		{
			MethodName: "TaskOutput",
			Handler:    _AgentService_TaskOutput_Handler,
		},
		{
			MethodName: "TaskStop",
			Handler:    _AgentService_TaskStop_Handler,
		},
		{
			MethodName: "FileGet",
			Handler:    _AgentService_FileGet_Handler,
		},
		{
			MethodName: "FilePut",
			Handler:    _AgentService_FilePut_Handler,
		},
		{
			MethodName: "FileMove",
			Handler:    _AgentService_FileMove_Handler,
		},
		{
			MethodName: "FileGetChunked",
			Handler:    _AgentService_FileGetChunked_Handler,
		},
		{
			MethodName: "FilePutChunked",
			Handler:    _AgentService_FilePutChunked_Handler,
		},
		{
			MethodName: "PortExpose",
			Handler:    _AgentService_PortExpose_Handler,
		},
		{
			MethodName: "PortUnexpose",
			Handler:    _AgentService_PortUnexpose_Handler,
		},
		{
			MethodName: "PortList",
			Handler:    _AgentService_PortList_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _AgentService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/agentd/v1/agent.proto",
}
